version: "3.9"
services:
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092 # How clients will connect to kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181            # ZK connection details
      - KAFKA_BROKER_ID=1                                 # Broker ID
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true              # Topics can be created by default
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1          # Consumer offset replication factor
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1                # Default topic replication factor
    restart: always
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.1
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181                       
    restart: always
  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_READONLY=false
  python_producer:
    build: .
    environment:
      - KAFKA_TOPIC=test            # Kafka topic to publish
      - KAFKA_BROKER=kafka:9092     # Kafka broker list
      - PUBLISH_DURATION=60         # The duration the application will produce to kafka
    command: python producer.py
    deploy:
      replicas: 2                   # The number of producer replicas we want

  python_consumer:
    build: .
    environment:
      - KAFKA_TOPIC=test            # Kafka topic to subscribe
      - KAFKA_BROKER=kafka:9092     # Kafka broker list
      - BATCH_SIZE=20               # Number of messages consumer will try and pull down from kafka (this sets number of threads too)
      - MULTI_THREAD=true           # Use threading if true
    command: python consumer.py
